/* hello_wayland: the smallest honest Wayland window -- now animated.
 *
 * Still the same four-step pipeline:
 *
 *   role -> configure/ack handshake -> buffer -> commit
 *
 * plus the pieces a real client adds on top:
 *
 *   - a continuous render loop paced by wl_surface.frame callbacks
 *   - double buffering: SLOTS buffers reused via wl_buffer.release
 *   - resize = fresh pool + fresh slot buffers; buffers still on loan
 *     to the compositor end their lives as orphans, destroyed once
 *     the release event arrives
 *
 * Reading order: main() at the bottom, then jump to each callback
 * as it is mentioned.
 */

#define _GNU_SOURCE /* for memfd_create */

#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#include <wayland-client.h>

#include "xdg-shell-client-protocol.h" /* generated by wayland-scanner */

enum { WIDTH = 640, HEIGHT = 360 }; /* fallback size when the compositor has no opinion */

/* Double buffering: one buffer on screen, one being drawn. Bump to 3
 * (triple buffering) if a compositor ever holds buffers long enough
 * that render() has to skip frames. */
enum { SLOTS = 2 };

struct slot {
    struct wl_buffer* buffer; /* this slot's CURRENT protocol object */
    int busy;                 /* committed and not yet released by the compositor */
};

struct state {
    /* connection + introduction phase */
    struct wl_display* display;
    struct wl_registry* registry;
    struct wl_compositor* compositor;
    struct wl_shm* shm;          /* shared-memory buffers (simplest kind) */
    struct xdg_wm_base* wm_base; /* the "make surfaces into windows" service */

    /* the window itself */
    struct wl_surface* surface;
    struct xdg_surface* xdg_surface;
    struct xdg_toplevel* toplevel;

    /* Pixel storage: ONE pool holding SLOTS buffers side by side,
     * recreated only when the size changes. Steady-state animation
     * allocates nothing -- the slots ping-pong forever. */
    struct wl_shm_pool* pool;
    uint32_t* pool_data; /* our mapping of the whole pool */
    size_t pool_bytes;
    struct slot slots[SLOTS];
    int buf_w, buf_h; /* size the slot buffers are currently created at */

    /* Window size. STAGED by xdg_toplevel.configure (data, no serial),
     * CONSUMED when we ack in xdg_surface.configure (serial, no data).
     * The compositor sends 0 for "you pick" -> fall back to WIDTH/HEIGHT. */
    int pending_w;
    int pending_h;

    uint32_t last_time; /* timestamp (ms) of the last frame callback */
    int animating;      /* frame-callback loop started? */
    int running;
};

/* ------------------------------------------------------------------ */
/* Step 0: the introduction phase -- read the menu, order what we     */
/* need.                                                              */
/* ------------------------------------------------------------------ */

static void on_global(void* data,
                      struct wl_registry* registry,
                      uint32_t name,
                      const char* interface,
                      uint32_t version) {
    struct state* st = data;
    (void)version;

    if (strcmp(interface, wl_compositor_interface.name) == 0) {
        /* v4: needed for wl_surface.damage_buffer below */
        st->compositor = wl_registry_bind(registry, name, &wl_compositor_interface, 4);
    } else if (strcmp(interface, wl_shm_interface.name) == 0) {
        st->shm = wl_registry_bind(registry, name, &wl_shm_interface, 1);
    } else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
        st->wm_base = wl_registry_bind(registry, name, &xdg_wm_base_interface, 1);
    }
}

static void on_global_remove(void* data, struct wl_registry* registry, uint32_t name) {
    (void)data;
    (void)registry;
    (void)name;
}

static const struct wl_registry_listener registry_listener = {
    .global = on_global,
    .global_remove = on_global_remove,
};

/* The liveness check: compositor pings, we must pong or be declared dead. */
static void on_wm_base_ping(void* data, struct xdg_wm_base* wm_base, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(wm_base, serial);
}

static const struct xdg_wm_base_listener wm_base_listener = {
    .ping = on_wm_base_ping,
};

/* ------------------------------------------------------------------ */
/* Step 3 (the buffers): pixel memory the compositor can see.         */
/*                                                                    */
/* wl_shm: we create a plain memory file (memfd), mmap it, draw into  */
/* it, and pass the fd over the socket. The compositor maps the same  */
/* file -> both sides see the same pixels, zero copy. Because of that */
/* sharing, a committed buffer is ON LOAN: we may not draw into it    */
/* again until the compositor returns it with wl_buffer.release.      */
/* Hence SLOTS buffers: draw into a free one while another is on      */
/* screen.                                                            */
/* ------------------------------------------------------------------ */

/* release: the compositor stopped reading this buffer. If it is still
 * a slot's current buffer, the slot is simply free again. If a resize
 * replaced it meanwhile, it is an orphan -- destroy it now. (We could
 * not destroy it earlier: the compositor was still reading the pages.) */
static void on_buffer_release(void* data, struct wl_buffer* buffer) {
    struct slot* s = data;
    if (s->buffer == buffer) {
        s->busy = 0;
    } else {
        wl_buffer_destroy(buffer);
    }
}

static const struct wl_buffer_listener buffer_listener = {
    .release = on_buffer_release,
};

/* Make pool + slot buffers exist at pending_w x pending_h. A resize
 * gets a FRESH pool instead of growing the old one in place: reusing
 * offsets in a grown pool could overlap a buffer the compositor is
 * still reading (one torn frame). Destroying the old pool object
 * immediately is explicitly legal -- each buffer keeps a reference to
 * its pool, so the storage lives until the last buffer dies. */
static void ensure_buffers(struct state* st) {
    const int w = st->pending_w;
    const int h = st->pending_h;
    if (st->pool && w == st->buf_w && h == st->buf_h) { return; }

    for (int i = 0; i < SLOTS; i++) {
        /* Free slots die now; busy ones become orphans for on_buffer_release. */
        if (st->slots[i].buffer && !st->slots[i].busy) { wl_buffer_destroy(st->slots[i].buffer); }
    }
    if (st->pool) {
        wl_shm_pool_destroy(st->pool);
        munmap(st->pool_data, st->pool_bytes);
    }

    const size_t slot_bytes = (size_t)w * 4 * h; /* 4 bytes per pixel: XRGB8888 */
    st->pool_bytes = slot_bytes * SLOTS;

    int fd = memfd_create("hello-wayland", 0);
    if (fd < 0 || ftruncate(fd, (off_t)st->pool_bytes) < 0) {
        perror("shm alloc");
        exit(1);
    }
    st->pool_data = mmap(NULL, st->pool_bytes, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (st->pool_data == MAP_FAILED) {
        perror("mmap");
        exit(1);
    }
    st->pool = wl_shm_create_pool(st->shm, fd, (int32_t)st->pool_bytes);
    close(fd); /* mappings + pool keep the pages alive; the fd may go */

    for (int i = 0; i < SLOTS; i++) {
        st->slots[i].buffer = wl_shm_pool_create_buffer(st->pool,
                                                        (int32_t)(i * slot_bytes),
                                                        w,
                                                        h,
                                                        w * 4,
                                                        WL_SHM_FORMAT_XRGB8888);
        wl_buffer_add_listener(st->slots[i].buffer, &buffer_listener, &st->slots[i]);
        st->slots[i].busy = 0;
    }
    st->buf_w = w;
    st->buf_h = h;
}

/* The actual "rendering": a diagonal gradient scrolling with time.
 * t is the compositor's frame timestamp in ms -- using it (instead of
 * our own clock) keeps the motion in step with the display even when
 * frames are skipped. */
static void fill_gradient(uint32_t* px, int w, int h, uint32_t t) {
    const uint32_t shift = t / 8;
    for (int y = 0; y < h; y++) {
        const uint32_t g = (uint32_t)y * 255 / (uint32_t)h;
        for (int x = 0; x < w; x++) {
            const uint32_t r = (((uint32_t)x * 255 / (uint32_t)w) + shift) & 255;
            const uint32_t b = 255 - r;
            px[(size_t)y * (size_t)w + (size_t)x] = (r << 16) | (g << 8) | b;
        }
    }
}

/* Draw one frame into a free slot and stage it on the surface (the
 * caller commits). If every slot is still on loan, skip this frame --
 * the next frame callback tries again. (This is exactly the situation
 * where SLOTS = 3 would help.) */
static void render(struct state* st) {
    struct slot* s = NULL;
    for (int i = 0; i < SLOTS; i++) {
        if (!st->slots[i].busy) {
            s = &st->slots[i];
            break;
        }
    }
    if (!s) { return; }

    uint32_t* px = st->pool_data + (size_t)(s - st->slots) * (size_t)st->buf_w * (size_t)st->buf_h;
    fill_gradient(px, st->buf_w, st->buf_h, st->last_time);

    wl_surface_attach(st->surface, s->buffer, 0, 0);
    /* attach alone does not tell the compositor what changed */
    wl_surface_damage_buffer(st->surface, 0, 0, INT32_MAX, INT32_MAX);
    s->busy = 1;
}

/* ------------------------------------------------------------------ */
/* The render loop: never draw on a timer. We ask the compositor for  */
/* a frame callback; it fires when drawing a new frame is worthwhile  */
/* (window visible, display about to refresh). Occluded window -> no  */
/* callbacks -> no wasted CPU. Each callback draws one frame and      */
/* requests the next one: request BEFORE commit, so the request is    */
/* part of the committed state.                                       */
/* ------------------------------------------------------------------ */

static void on_frame_done(void* data, struct wl_callback* cb, uint32_t time_ms);

static const struct wl_callback_listener frame_listener = {
    .done = on_frame_done,
};

static void schedule_frame(struct state* st) {
    struct wl_callback* cb = wl_surface_frame(st->surface);
    wl_callback_add_listener(cb, &frame_listener, st);
}

static void on_frame_done(void* data, struct wl_callback* cb, uint32_t time_ms) {
    struct state* st = data;
    wl_callback_destroy(cb); /* frame callbacks are one-shot */
    st->last_time = time_ms;

    schedule_frame(st);
    render(st);
    wl_surface_commit(st->surface);
}

/* ------------------------------------------------------------------ */
/* Step 2 (the handshake): the compositor answers our first commit    */
/* with a configure event. We must ack it, quoting its serial. Only   */
/* then may the surface carry content -- so this callback is also     */
/* where the first frame is drawn and the render loop is started.     */
/* The commit at the end is the mapping moment: this is when the      */
/* window appears on screen.                                          */
/*                                                                    */
/* The same callback serves every later resize: toplevel configure    */
/* staged pending_w/h, our ack promises "commits from now on answer   */
/* serial N", and we draw at the staged size -- so the compositor can */
/* swap geometry and content atomically in one frame.                 */
/* ------------------------------------------------------------------ */

static void on_xdg_surface_configure(void* data, struct xdg_surface* xdg_surface, uint32_t serial) {
    struct state* st = data;

    xdg_surface_ack_configure(xdg_surface, serial);

    ensure_buffers(st);
    if (!st->animating) {
        st->animating = 1;
        schedule_frame(st);
    }
    render(st);
    wl_surface_commit(st->surface);
}

static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = on_xdg_surface_configure,
};

/* Toplevel events: the compositor's size proposal and the close button.
 *
 * configure carries the DATA (w, h, states -- signature "iia") but no
 * serial: it only STAGES state, mirroring how our own requests are
 * pending until commit. Nothing is applied here; xdg_surface.configure
 * ends the batch and tells us when to act. */
static void on_toplevel_configure(void* data,
                                  struct xdg_toplevel* toplevel,
                                  int32_t w,
                                  int32_t h,
                                  struct wl_array* states) {
    (void)toplevel;
    (void)states; /* maximized/activated/resizing/... -- unused here */
    struct state* st = data;

    /* 0 means "you pick" -- typical for the very first configure,
     * which answers our empty commit. */
    st->pending_w = w > 0 ? w : WIDTH;
    st->pending_h = h > 0 ? h : HEIGHT;
}

static void on_toplevel_close(void* data, struct xdg_toplevel* toplevel) {
    (void)toplevel;
    struct state* st = data;
    st->running = 0;
}

static const struct xdg_toplevel_listener toplevel_listener = {
    .configure = on_toplevel_configure,
    .close = on_toplevel_close,
};

/* ------------------------------------------------------------------ */

int main(void) {
    struct state st = {0};
    st.running = 1;
    st.pending_w = WIDTH;
    st.pending_h = HEIGHT;

    /* Pick up the phone line. */
    st.display = wl_display_connect(NULL);
    if (!st.display) {
        fprintf(stderr, "no Wayland display (is WAYLAND_DISPLAY set?)\n");
        return 1;
    }

    /* Introduction phase: listen to the menu, bind services.
     * One roundtrip is enough here -- none of our three globals
     * sends initial events on bind. */
    st.registry = wl_display_get_registry(st.display);
    wl_registry_add_listener(st.registry, &registry_listener, &st);
    wl_display_roundtrip(st.display);

    if (!st.compositor || !st.shm || !st.wm_base) {
        fprintf(stderr, "missing wl_compositor, wl_shm or xdg_wm_base\n");
        return 1;
    }
    xdg_wm_base_add_listener(st.wm_base, &wm_base_listener, &st);

    /* Step 0.5: the blank canvas. */
    st.surface = wl_compositor_create_surface(st.compositor);

    /* Step 1: give it a role. Surface -> xdg_surface -> toplevel. */
    st.xdg_surface = xdg_wm_base_get_xdg_surface(st.wm_base, st.surface);
    xdg_surface_add_listener(st.xdg_surface, &xdg_surface_listener, &st);

    st.toplevel = xdg_surface_get_toplevel(st.xdg_surface);
    xdg_toplevel_add_listener(st.toplevel, &toplevel_listener, &st);
    xdg_toplevel_set_title(st.toplevel, "hello wayland");
    xdg_toplevel_set_app_id(st.toplevel, "hello-wayland");

    /* First commit: still WITHOUT a buffer. This tells the compositor
     * "role assigned, please configure me". The reply arrives as the
     * configure event -> on_xdg_surface_configure above. */
    wl_surface_commit(st.surface);

    /* The event loop: block, read mail, run callbacks, repeat.
     * Everything from here on happens inside the listeners. */
    while (st.running && wl_display_dispatch(st.display) != -1) {}

    /* Teardown mirror: buffers before pool, pool before the globals. */
    for (int i = 0; i < SLOTS; i++) {
        if (st.slots[i].buffer) { wl_buffer_destroy(st.slots[i].buffer); }
    }
    if (st.pool) {
        wl_shm_pool_destroy(st.pool);
        munmap(st.pool_data, st.pool_bytes);
    }
    xdg_toplevel_destroy(st.toplevel);
    xdg_surface_destroy(st.xdg_surface);
    wl_surface_destroy(st.surface);
    xdg_wm_base_destroy(st.wm_base);
    wl_shm_destroy(st.shm);
    wl_compositor_destroy(st.compositor);
    wl_registry_destroy(st.registry);
    wl_display_disconnect(st.display);
    return 0;
}
