/* hello_wayland: the smallest honest Wayland window -- now animated
 * and interactive.
 *
 * Still the same four-step pipeline:
 *
 *   role -> configure/ack handshake -> buffer -> commit
 *
 * plus the pieces a real client adds on top:
 *
 *   - a continuous render loop paced by wl_surface.frame callbacks
 *   - buffering: SLOTS buffers reused via wl_buffer.release
 *   - resize = fresh pool + fresh slot buffers; buffers still on loan
 *     to the compositor end their lives as orphans, destroyed once
 *     the release event arrives
 *   - input via wl_seat: pointer steers the gradient (left-drag moves
 *     the window, scroll changes speed), keyboard via xkbcommon
 *     (Space pauses, Esc/Q quits)
 *
 * Reading order: main() at the bottom, then jump to each callback
 * as it is mentioned.
 */

#define _GNU_SOURCE /* for memfd_create */

#include <fcntl.h>
#include <linux/input-event-codes.h> /* BTN_LEFT -- pointer buttons are evdev codes */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#include <wayland-client.h>
#include <wayland-cursor.h>
#include <xkbcommon/xkbcommon.h>

#include "xdg-shell-client-protocol.h" /* generated by wayland-scanner */

enum { WIDTH = 640, HEIGHT = 360 }; /* fallback size when the compositor has no opinion */

/* Double buffering: one buffer on screen, one being drawn. Bump to 3
 * (triple buffering) if a compositor ever holds buffers long enough
 * that render() has to skip frames. */
enum { SLOTS = 1 };

struct slot {
    struct wl_buffer* buffer; /* this slot's CURRENT protocol object */
    int busy;                 /* committed and not yet released by the compositor */
};

/* One batched pointer transaction (seat v5+). The wl_pointer event
 * handlers only STAGE fields here; wl_pointer.frame APPLIES them as
 * one atomic update -- the same stage/apply discipline as surface
 * commit and configure/ack, now in the input direction. */
enum {
    PTR_MOTION = 1 << 0, /* x/y valid (enter or motion) */
    PTR_BUTTON = 1 << 1, /* button/button_state/serial valid */
    PTR_AXIS_V = 1 << 2, /* axis_v valid */
};

struct pointer_event {
    uint32_t mask;         /* which of the fields this frame touched */
    double x, y;           /* latest position within the frame */
    uint32_t button;       /* evdev button code (BTN_LEFT, ...) */
    uint32_t button_state; /* pressed or released */
    uint32_t serial;       /* of the button event -- authorizes moves */
    double axis_v;         /* vertical scroll, summed over the frame */
};

struct state {
    /* connection + introduction phase */
    struct wl_display* display;
    struct wl_registry* registry;
    struct wl_compositor* compositor;
    struct wl_shm* shm;          /* shared-memory buffers (simplest kind) */
    struct xdg_wm_base* wm_base; /* the "make surfaces into windows" service */

    /* the window itself */
    struct wl_surface* surface;
    struct xdg_surface* xdg_surface;
    struct xdg_toplevel* toplevel;

    /* input: one seat = one user (pointer + keyboard + touch caps) */
    struct wl_seat* seat;
    struct wl_pointer* pointer;
    struct wl_keyboard* keyboard;
    struct xkb_context* xkb_context;
    struct xkb_keymap* xkb_keymap;
    struct xkb_state* xkb_state;
    double ptr_x, ptr_y;            /* last APPLIED pointer position */
    struct pointer_event ptr_event; /* the staged, not-yet-applied batch */

    /* The cursor: one more wl_surface with one more (theme-provided)
     * shm buffer. We commit it once; the compositor moves it. */
    struct wl_cursor_theme* cursor_theme;
    struct wl_surface* cursor_surface;
    struct wl_cursor_image* cursor_image; /* kept for the hotspot */

    /* Pixel storage: ONE pool holding SLOTS buffers side by side,
     * recreated only when the size changes. Steady-state animation
     * allocates nothing -- the slots ping-pong forever. */
    struct wl_shm_pool* pool;
    uint32_t* pool_data; /* our mapping of the whole pool */
    size_t pool_bytes;
    struct slot slots[SLOTS];
    int buf_w, buf_h; /* size the slot buffers are currently created at */

    /* Window size. STAGED by xdg_toplevel.configure (data, no serial),
     * CONSUMED when we ack in xdg_surface.configure (serial, no data).
     * The compositor sends 0 for "you pick" -> fall back to WIDTH/HEIGHT. */
    int pending_w;
    int pending_h;

    uint32_t last_time; /* timestamp (ms) of the last frame callback */
    double anim_ms;     /* animation clock: pausable and speed-scalable */
    double speed;       /* scroll wheel adjusts; negative runs backwards */
    int paused;         /* Space toggles */
    int animating;      /* frame-callback loop started? */
    int running;
};

/* ------------------------------------------------------------------ */
/* Step 0: the introduction phase -- read the menu, order what we     */
/* need.                                                              */
/* ------------------------------------------------------------------ */

static void on_global(void* data,
                      struct wl_registry* registry,
                      uint32_t name,
                      const char* interface,
                      uint32_t version) {
    struct state* st = data;

    if (strcmp(interface, wl_compositor_interface.name) == 0) {
        /* v4: needed for wl_surface.damage_buffer below */
        st->compositor = wl_registry_bind(registry, name, &wl_compositor_interface, 4);
    } else if (strcmp(interface, wl_shm_interface.name) == 0) {
        st->shm = wl_registry_bind(registry, name, &wl_shm_interface, 1);
    } else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
        st->wm_base = wl_registry_bind(registry, name, &xdg_wm_base_interface, 1);
    } else if (strcmp(interface, wl_seat_interface.name) == 0) {
        /* First real use of the version argument: negotiate
         * min(server, what we implement). v5 pointer objects batch
         * events into frames (see on_pointer_frame). */
        st->seat = wl_registry_bind(registry, name, &wl_seat_interface, version < 5 ? version : 5);
    }
}

static void on_global_remove(void* data, struct wl_registry* registry, uint32_t name) {
    (void)data;
    (void)registry;
    (void)name;
}

static const struct wl_registry_listener registry_listener = {
    .global = on_global,
    .global_remove = on_global_remove,
};

/* The liveness check: compositor pings, we must pong or be declared dead. */
static void on_wm_base_ping(void* data, struct xdg_wm_base* wm_base, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(wm_base, serial);
}

static const struct xdg_wm_base_listener wm_base_listener = {
    .ping = on_wm_base_ping,
};

/* ------------------------------------------------------------------ */
/* Input, part 1: the keyboard.                                       */
/*                                                                    */
/* Wayland deliberately sends RAW scancodes -- interpreting them      */
/* needs the keymap, and the keymap arrives as... a file descriptor.  */
/* The same trick as our pixel buffers, in the other direction: the   */
/* compositor shares one memfd holding the xkb keymap text and every  */
/* client maps the same copy. xkbcommon compiles it and translates    */
/* scancode -> keysym, honoring layout and modifiers.                 */
/* ------------------------------------------------------------------ */

static void on_keyboard_keymap(void* data,
                               struct wl_keyboard* keyboard,
                               uint32_t format,
                               int32_t fd,
                               uint32_t size) {
    (void)keyboard;
    struct state* st = data;

    if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) {
        close(fd);
        return;
    }

    char* map = mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (map == MAP_FAILED) {
        close(fd);
        return;
    }

    /* Keymaps can change at runtime (layout switch) -> replace, not set. */
    xkb_state_unref(st->xkb_state);
    xkb_keymap_unref(st->xkb_keymap);
    st->xkb_keymap = xkb_keymap_new_from_string(st->xkb_context,
                                                map,
                                                XKB_KEYMAP_FORMAT_TEXT_V1,
                                                XKB_KEYMAP_COMPILE_NO_FLAGS);
    st->xkb_state = st->xkb_keymap ? xkb_state_new(st->xkb_keymap) : NULL;

    munmap(map, size);
    close(fd);
}

static void on_keyboard_enter(void* data,
                              struct wl_keyboard* keyboard,
                              uint32_t serial,
                              struct wl_surface* surface,
                              struct wl_array* keys) {
    (void)data;
    (void)keyboard;
    (void)serial;
    (void)surface;
    (void)keys; /* keys already held when focus arrived -- a real app
                 * would process these to avoid missing chords */
}

static void on_keyboard_leave(void* data,
                              struct wl_keyboard* keyboard,
                              uint32_t serial,
                              struct wl_surface* surface) {
    (void)data;
    (void)keyboard;
    (void)serial;
    (void)surface;
}

static void on_keyboard_key(void* data,
                            struct wl_keyboard* keyboard,
                            uint32_t serial,
                            uint32_t time,
                            uint32_t key,
                            uint32_t key_state) {
    (void)keyboard;
    (void)serial;
    (void)time;
    struct state* st = data;

    if (key_state != WL_KEYBOARD_KEY_STATE_PRESSED || !st->xkb_state) { return; }

    /* wl_keyboard delivers evdev scancodes; xkb keycodes are evdev + 8
     * (a fossilized X11 offset). */
    xkb_keysym_t sym = xkb_state_key_get_one_sym(st->xkb_state, key + 8);
    switch (sym) {
        case XKB_KEY_Escape:
        case XKB_KEY_q: st->running = 0; break;
        case XKB_KEY_space: st->paused = !st->paused; break;
        default: break;
    }
}

static void on_keyboard_modifiers(void* data,
                                  struct wl_keyboard* keyboard,
                                  uint32_t serial,
                                  uint32_t mods_depressed,
                                  uint32_t mods_latched,
                                  uint32_t mods_locked,
                                  uint32_t group) {
    (void)keyboard;
    (void)serial;
    struct state* st = data;

    /* Feed modifier state to xkb so Shift+q still means 'Q' etc. */
    if (st->xkb_state) {
        xkb_state_update_mask(st->xkb_state,
                              mods_depressed,
                              mods_latched,
                              mods_locked,
                              0,
                              0,
                              group);
    }
}

static void on_keyboard_repeat_info(void* data,
                                    struct wl_keyboard* keyboard,
                                    int32_t rate,
                                    int32_t delay) {
    (void)data;
    (void)keyboard;
    (void)rate;
    (void)delay; /* key REPEAT is the client's job on Wayland; a real
                  * app arms a timer from these values. We skip it. */
}

static const struct wl_keyboard_listener keyboard_listener = {
    .keymap = on_keyboard_keymap,
    .enter = on_keyboard_enter,
    .leave = on_keyboard_leave,
    .key = on_keyboard_key,
    .modifiers = on_keyboard_modifiers,
    .repeat_info = on_keyboard_repeat_info,
};

/* ------------------------------------------------------------------ */
/* Input, part 2: the pointer.                                        */
/*                                                                    */
/* Coordinates are surface-local, as wl_fixed_t (24.8 fixed point).   */
/* Since v5 the events are BATCHED: enter/motion/axis... describe one */
/* hardware event together and wl_pointer.frame terminates the batch. */
/* The handlers below therefore only STAGE into st->ptr_event; all    */
/* application state changes happen in on_pointer_frame. This is what */
/* keeps a diagonal touchpad scroll (two axis events, one frame) one  */
/* gesture instead of an L-shaped pair.                               */
/* ------------------------------------------------------------------ */

static void on_pointer_enter(void* data,
                             struct wl_pointer* pointer,
                             uint32_t serial,
                             struct wl_surface* surface,
                             wl_fixed_t sx,
                             wl_fixed_t sy) {
    (void)surface;
    struct state* st = data;

    /* STAGE the entry position; applied in on_pointer_frame. */
    st->ptr_event.mask |= PTR_MOTION;
    st->ptr_event.x = wl_fixed_to_double(sx);
    st->ptr_event.y = wl_fixed_to_double(sy);

    /* set_cursor is NOT application state, it is the protocol reply to
     * this enter (like pong answers ping), quoting the enter serial --
     * so it does not wait for the frame event. */

    /* Inside our window the cursor image is OUR responsibility -- the
     * compositor draws no default. We hand it our cursor surface plus
     * the HOTSPOT: which pixel of the image is the logical tip (an
     * arrow points top-left, a crosshair centers). The serial proves
     * we answer THIS enter, not a stale one. NULL would hide the
     * cursor; cursor-shape-v1 is the modern way to skip all of this
     * and name a shape for the compositor to draw. */
    if (st->cursor_surface) {
        wl_pointer_set_cursor(pointer,
                              serial,
                              st->cursor_surface,
                              (int32_t)st->cursor_image->hotspot_x,
                              (int32_t)st->cursor_image->hotspot_y);
    } else {
        wl_pointer_set_cursor(pointer, serial, NULL, 0, 0);
    }
}

static void on_pointer_leave(void* data,
                             struct wl_pointer* pointer,
                             uint32_t serial,
                             struct wl_surface* surface) {
    (void)data;
    (void)pointer;
    (void)serial;
    (void)surface;
}

static void on_pointer_motion(void* data,
                              struct wl_pointer* pointer,
                              uint32_t time,
                              wl_fixed_t sx,
                              wl_fixed_t sy) {
    (void)pointer;
    (void)time;
    struct state* st = data;

    /* STAGE only -- multiple fields of one hardware event (motion +
     * axis of a touchpad gesture) must land together, at the frame. */
    st->ptr_event.mask |= PTR_MOTION;
    st->ptr_event.x = wl_fixed_to_double(sx);
    st->ptr_event.y = wl_fixed_to_double(sy);
}

static void on_pointer_button(void* data,
                              struct wl_pointer* pointer,
                              uint32_t serial,
                              uint32_t time,
                              uint32_t button,
                              uint32_t button_state) {
    (void)pointer;
    (void)time;
    struct state* st = data;

    /* STAGE. Two buttons in one frame would overwrite each other --
     * a real toolkit keeps a small list; one is plenty here. */
    st->ptr_event.mask |= PTR_BUTTON;
    st->ptr_event.button = button;
    st->ptr_event.button_state = button_state;
    st->ptr_event.serial = serial;
}

static void on_pointer_axis(void* data,
                            struct wl_pointer* pointer,
                            uint32_t time,
                            uint32_t axis,
                            wl_fixed_t value) {
    (void)pointer;
    (void)time;
    struct state* st = data;

    if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL) {
        /* STAGE, and SUM: one frame may carry several axis events. */
        st->ptr_event.mask |= PTR_AXIS_V;
        st->ptr_event.axis_v += wl_fixed_to_double(value);
    }
}

/* End of one batched pointer transaction: APPLY the staged fields as
 * a single atomic update, then clear the staging area. (Pre-v5 servers
 * never send frame; a fully portable app applies after every event
 * when wl_pointer_get_version() < 5 -- omitted here, we bind v5.) */
static void on_pointer_frame(void* data, struct wl_pointer* pointer) {
    (void)pointer;
    struct state* st = data;
    struct pointer_event* ev = &st->ptr_event;

    if (ev->mask & PTR_MOTION) {
        st->ptr_x = ev->x;
        st->ptr_y = ev->y;
    }

    if ((ev->mask & PTR_BUTTON) && ev->button == BTN_LEFT &&
        ev->button_state == WL_POINTER_BUTTON_STATE_PRESSED) {
        /* Hand the drag to the compositor. The serial is the key: it
         * proves we act on FRESH user input -- the compositor honors
         * move/resize only against a recent input serial, so apps
         * cannot fling windows around spontaneously. */
        xdg_toplevel_move(st->toplevel, st->seat, ev->serial);
    }

    if (ev->mask & PTR_AXIS_V) {
        /* scroll up = faster, down = slower; through zero into reverse */
        st->speed -= ev->axis_v / 20.0;
        if (st->speed > 10.0) { st->speed = 10.0; }
        if (st->speed < -10.0) { st->speed = -10.0; }
    }

    memset(ev, 0, sizeof(*ev)); /* transaction consumed */
}

static void on_pointer_axis_source(void* data, struct wl_pointer* pointer, uint32_t source) {
    (void)data;
    (void)pointer;
    (void)source;
}

static void on_pointer_axis_stop(void* data,
                                 struct wl_pointer* pointer,
                                 uint32_t time,
                                 uint32_t axis) {
    (void)data;
    (void)pointer;
    (void)time;
    (void)axis;
}

static void on_pointer_axis_discrete(void* data,
                                     struct wl_pointer* pointer,
                                     uint32_t axis,
                                     int32_t discrete) {
    (void)data;
    (void)pointer;
    (void)axis;
    (void)discrete;
}

static const struct wl_pointer_listener pointer_listener = {
    .enter = on_pointer_enter,
    .leave = on_pointer_leave,
    .motion = on_pointer_motion,
    .button = on_pointer_button,
    .axis = on_pointer_axis,
    .frame = on_pointer_frame,
    .axis_source = on_pointer_axis_source,
    .axis_stop = on_pointer_axis_stop,
    .axis_discrete = on_pointer_axis_discrete,
};

/* ------------------------------------------------------------------ */
/* Input, part 3: the seat ties it together. Capabilities are DYNAMIC */
/* -- unplug the mouse and this fires again without the pointer bit,  */
/* so both directions (get/release) are handled.                      */
/* ------------------------------------------------------------------ */

static void on_seat_capabilities(void* data, struct wl_seat* seat, uint32_t caps) {
    struct state* st = data;

    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !st->pointer) {
        st->pointer = wl_seat_get_pointer(seat);
        wl_pointer_add_listener(st->pointer, &pointer_listener, st);
    } else if (!(caps & WL_SEAT_CAPABILITY_POINTER) && st->pointer) {
        wl_pointer_release(st->pointer);
        st->pointer = NULL;
    }

    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !st->keyboard) {
        st->keyboard = wl_seat_get_keyboard(seat);
        wl_keyboard_add_listener(st->keyboard, &keyboard_listener, st);
    } else if (!(caps & WL_SEAT_CAPABILITY_KEYBOARD) && st->keyboard) {
        wl_keyboard_release(st->keyboard);
        st->keyboard = NULL;
    }
}

static void on_seat_name(void* data, struct wl_seat* seat, const char* name) {
    (void)data;
    (void)seat;
    (void)name;
}

static const struct wl_seat_listener seat_listener = {
    .capabilities = on_seat_capabilities,
    .name = on_seat_name,
};

/* ------------------------------------------------------------------ */
/* Step 3 (the buffers): pixel memory the compositor can see.         */
/*                                                                    */
/* wl_shm: we create a plain memory file (memfd), mmap it, draw into  */
/* it, and pass the fd over the socket. The compositor maps the same  */
/* file -> both sides see the same pixels, zero copy. Because of that */
/* sharing, a committed buffer is ON LOAN: we may not draw into it    */
/* again until the compositor returns it with wl_buffer.release.      */
/* Hence SLOTS buffers: draw into a free one while another is on      */
/* screen.                                                            */
/* ------------------------------------------------------------------ */

/* release: the compositor stopped reading this buffer. If it is still
 * a slot's current buffer, the slot is simply free again. If a resize
 * replaced it meanwhile, it is an orphan -- destroy it now. (We could
 * not destroy it earlier: the compositor was still reading the pages.) */
static void on_buffer_release(void* data, struct wl_buffer* buffer) {
    struct slot* s = data;
    if (s->buffer == buffer) {
        s->busy = 0;
    } else {
        wl_buffer_destroy(buffer);
    }
}

static const struct wl_buffer_listener buffer_listener = {
    .release = on_buffer_release,
};

/* Make pool + slot buffers exist at pending_w x pending_h. A resize
 * gets a FRESH pool instead of growing the old one in place: reusing
 * offsets in a grown pool could overlap a buffer the compositor is
 * still reading (one torn frame). Destroying the old pool object
 * immediately is explicitly legal -- each buffer keeps a reference to
 * its pool, so the storage lives until the last buffer dies. */
static void ensure_buffers(struct state* st) {
    const int w = st->pending_w;
    const int h = st->pending_h;
    if (st->pool && w == st->buf_w && h == st->buf_h) { return; }

    for (int i = 0; i < SLOTS; i++) {
        /* Free slots die now; busy ones become orphans for on_buffer_release. */
        if (st->slots[i].buffer && !st->slots[i].busy) { wl_buffer_destroy(st->slots[i].buffer); }
    }
    if (st->pool) {
        wl_shm_pool_destroy(st->pool);
        munmap(st->pool_data, st->pool_bytes);
    }

    const size_t slot_bytes = (size_t)w * 4 * h; /* 4 bytes per pixel: XRGB8888 */
    st->pool_bytes = slot_bytes * SLOTS;

    int fd = memfd_create("hello-wayland", 0);
    if (fd < 0 || ftruncate(fd, (off_t)st->pool_bytes) < 0) {
        perror("shm alloc");
        exit(1);
    }
    st->pool_data = mmap(NULL, st->pool_bytes, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (st->pool_data == MAP_FAILED) {
        perror("mmap");
        exit(1);
    }
    st->pool = wl_shm_create_pool(st->shm, fd, (int32_t)st->pool_bytes);
    close(fd); /* mappings + pool keep the pages alive; the fd may go */

    for (int i = 0; i < SLOTS; i++) {
        st->slots[i].buffer = wl_shm_pool_create_buffer(st->pool,
                                                        (int32_t)(i * slot_bytes),
                                                        w,
                                                        h,
                                                        w * 4,
                                                        WL_SHM_FORMAT_XRGB8888);
        wl_buffer_add_listener(st->slots[i].buffer, &buffer_listener, &st->slots[i]);
        st->slots[i].busy = 0;
    }
    st->buf_w = w;
    st->buf_h = h;
}

/* The actual "rendering": a diagonal gradient scrolling with time,
 * its origin pinned to the pointer. t comes from the pausable,
 * speed-scaled animation clock. */
static void fill_gradient(uint32_t* px, int w, int h, uint32_t t, int cx, int cy) {
    const int shift = (int)(t / 8);
    for (int y = 0; y < h; y++) {
        const uint32_t g = (uint32_t)(((y - cy) * 255 / h) & 255);
        for (int x = 0; x < w; x++) {
            const uint32_t r = (uint32_t)((((x - cx) * 255 / w) + shift) & 255);
            const uint32_t b = 255 - r;
            px[(size_t)y * (size_t)w + (size_t)x] = (r << 16) | (g << 8) | b;
        }
    }
}

/* Draw one frame into a free slot and stage it on the surface (the
 * caller commits). If every slot is still on loan, skip this frame --
 * the next frame callback tries again. (This is exactly the situation
 * where more SLOTS would help.) */
static void render(struct state* st) {
    struct slot* s = NULL;
    for (int i = 0; i < SLOTS; i++) {
        if (!st->slots[i].busy) {
            s = &st->slots[i];
            break;
        }
    }
    if (!s) { return; }

    uint32_t* px = st->pool_data + (size_t)(s - st->slots) * (size_t)st->buf_w * (size_t)st->buf_h;
    fill_gradient(px,
                  st->buf_w,
                  st->buf_h,
                  (uint32_t)(int64_t)st->anim_ms,
                  (int)st->ptr_x,
                  (int)st->ptr_y);

    wl_surface_attach(st->surface, s->buffer, 0, 0);
    /* attach alone does not tell the compositor what changed */
    wl_surface_damage_buffer(st->surface, 0, 0, INT32_MAX, INT32_MAX);
    s->busy = 1;
}

/* ------------------------------------------------------------------ */
/* The render loop: never draw on a timer. We ask the compositor for  */
/* a frame callback; it fires when drawing a new frame is worthwhile  */
/* (window visible, display about to refresh). Occluded window -> no  */
/* callbacks -> no wasted CPU. Each callback draws one frame and      */
/* requests the next one: request BEFORE commit, so the request is    */
/* part of the committed state.                                       */
/* ------------------------------------------------------------------ */

static void on_frame_done(void* data, struct wl_callback* cb, uint32_t time_ms);

static const struct wl_callback_listener frame_listener = {
    .done = on_frame_done,
};

static void schedule_frame(struct state* st) {
    struct wl_callback* cb = wl_surface_frame(st->surface);
    wl_callback_add_listener(cb, &frame_listener, st);
}

static void on_frame_done(void* data, struct wl_callback* cb, uint32_t time_ms) {
    struct state* st = data;
    wl_callback_destroy(cb); /* frame callbacks are one-shot */

    /* Advance the animation clock by scaled wall time. Pausing or
     * scrolling never causes a jump: the clock only ever accumulates. */
    if (st->last_time != 0 && !st->paused) {
        st->anim_ms += (double)(time_ms - st->last_time) * st->speed;
    }
    st->last_time = time_ms;

    schedule_frame(st);
    render(st);
    wl_surface_commit(st->surface);
}

/* ------------------------------------------------------------------ */
/* Step 2 (the handshake): the compositor answers our first commit    */
/* with a configure event. We must ack it, quoting its serial. Only   */
/* then may the surface carry content -- so this callback is also     */
/* where the first frame is drawn and the render loop is started.     */
/* The commit at the end is the mapping moment: this is when the      */
/* window appears on screen.                                          */
/*                                                                    */
/* The same callback serves every later resize: toplevel configure    */
/* staged pending_w/h, our ack promises "commits from now on answer   */
/* serial N", and we draw at the staged size -- so the compositor can */
/* swap geometry and content atomically in one frame.                 */
/* ------------------------------------------------------------------ */

static void on_xdg_surface_configure(void* data, struct xdg_surface* xdg_surface, uint32_t serial) {
    struct state* st = data;

    xdg_surface_ack_configure(xdg_surface, serial);

    ensure_buffers(st);
    if (!st->animating) {
        st->animating = 1;
        schedule_frame(st);
    }
    render(st);
    wl_surface_commit(st->surface);
}

static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = on_xdg_surface_configure,
};

/* Toplevel events: the compositor's size proposal and the close button.
 *
 * configure carries the DATA (w, h, states -- signature "iia") but no
 * serial: it only STAGES state, mirroring how our own requests are
 * pending until commit. Nothing is applied here; xdg_surface.configure
 * ends the batch and tells us when to act. */
static void on_toplevel_configure(void* data,
                                  struct xdg_toplevel* toplevel,
                                  int32_t w,
                                  int32_t h,
                                  struct wl_array* states) {
    (void)toplevel;
    (void)states; /* maximized/activated/resizing/... -- unused here */
    struct state* st = data;

    /* 0 means "you pick" -- typical for the very first configure,
     * which answers our empty commit. */
    st->pending_w = w > 0 ? w : WIDTH;
    st->pending_h = h > 0 ? h : HEIGHT;
}

static void on_toplevel_close(void* data, struct xdg_toplevel* toplevel) {
    (void)toplevel;
    struct state* st = data;
    st->running = 0;
}

static const struct xdg_toplevel_listener toplevel_listener = {
    .configure = on_toplevel_configure,
    .close = on_toplevel_close,
};

/* ------------------------------------------------------------------ */

int main(void) {
    struct state st = {0};
    st.running = 1;
    st.speed = 1.0;
    st.pending_w = WIDTH;
    st.pending_h = HEIGHT;

    /* Pick up the phone line. */
    st.display = wl_display_connect(NULL);
    if (!st.display) {
        fprintf(stderr, "no Wayland display (is WAYLAND_DISPLAY set?)\n");
        return 1;
    }

    /* Introduction phase: listen to the menu, bind services. One
     * roundtrip is enough: the seat's initial events (capabilities)
     * arrive later in the main loop, before any input can happen. */
    st.registry = wl_display_get_registry(st.display);
    wl_registry_add_listener(st.registry, &registry_listener, &st);
    wl_display_roundtrip(st.display);

    if (!st.compositor || !st.shm || !st.wm_base) {
        fprintf(stderr, "missing wl_compositor, wl_shm or xdg_wm_base\n");
        return 1;
    }
    xdg_wm_base_add_listener(st.wm_base, &wm_base_listener, &st);

    /* Input is optional (headless compositors have no seat). */
    if (st.seat) {
        wl_seat_add_listener(st.seat, &seat_listener, &st);
        st.xkb_context = xkb_context_new(XKB_CONTEXT_NO_FLAGS);

        /* The cursor, demystified: libwayland-cursor loads the XCursor
         * theme from disk into ITS OWN shm pool and hands us finished
         * wl_buffers. We attach one to a surface exactly like our
         * window content -- attach, damage, commit -- and never touch
         * it again. set_cursor (on pointer enter) gives this surface
         * the CURSOR role, the pointer-world sibling of xdg_toplevel:
         * same surface, different role, so no configure handshake --
         * the compositor decides its position, not us. */
        const char* size_env = getenv("XCURSOR_SIZE");
        int cursor_size = size_env ? atoi(size_env) : 0;
        if (cursor_size <= 0) { cursor_size = 24; }

        st.cursor_theme = wl_cursor_theme_load(NULL, cursor_size, st.shm);
        struct wl_cursor* cursor =
            st.cursor_theme ? wl_cursor_theme_get_cursor(st.cursor_theme, "default") : NULL;
        if (!cursor) { /* older themes use the X11 name */
            cursor =
                st.cursor_theme ? wl_cursor_theme_get_cursor(st.cursor_theme, "left_ptr") : NULL;
        }
        if (cursor && cursor->image_count > 0) {
            /* images[1..n] would be an ANIMATED cursor (each frame has
             * a delay); we show the first frame only. */
            st.cursor_image = cursor->images[0];
            st.cursor_surface = wl_compositor_create_surface(st.compositor);
            wl_surface_attach(st.cursor_surface, wl_cursor_image_get_buffer(st.cursor_image), 0, 0);
            wl_surface_damage_buffer(st.cursor_surface, 0, 0, INT32_MAX, INT32_MAX);
            wl_surface_commit(st.cursor_surface);
        } else {
            fprintf(stderr, "no cursor theme found -- cursor will be hidden\n");
        }
    }

    /* Step 0.5: the blank canvas. */
    st.surface = wl_compositor_create_surface(st.compositor);

    /* Step 1: give it a role. Surface -> xdg_surface -> toplevel. */
    st.xdg_surface = xdg_wm_base_get_xdg_surface(st.wm_base, st.surface);
    xdg_surface_add_listener(st.xdg_surface, &xdg_surface_listener, &st);

    st.toplevel = xdg_surface_get_toplevel(st.xdg_surface);
    xdg_toplevel_add_listener(st.toplevel, &toplevel_listener, &st);
    xdg_toplevel_set_title(st.toplevel, "hello wayland");
    xdg_toplevel_set_app_id(st.toplevel, "hello-wayland");

    /* First commit: still WITHOUT a buffer. This tells the compositor
     * "role assigned, please configure me". The reply arrives as the
     * configure event -> on_xdg_surface_configure above. */
    wl_surface_commit(st.surface);

    /* The event loop: block, read mail, run callbacks, repeat.
     * Everything from here on happens inside the listeners. */
    while (st.running && wl_display_dispatch(st.display) != -1) {}

    /* Teardown mirror: buffers before pool, pool before the globals. */
    for (int i = 0; i < SLOTS; i++) {
        if (st.slots[i].buffer) { wl_buffer_destroy(st.slots[i].buffer); }
    }
    if (st.pool) {
        wl_shm_pool_destroy(st.pool);
        munmap(st.pool_data, st.pool_bytes);
    }
    if (st.pointer) { wl_pointer_release(st.pointer); }
    if (st.keyboard) { wl_keyboard_release(st.keyboard); }
    if (st.seat) { wl_seat_destroy(st.seat); }
    if (st.cursor_surface) { wl_surface_destroy(st.cursor_surface); }
    if (st.cursor_theme) { wl_cursor_theme_destroy(st.cursor_theme); } /* owns the buffers */
    xkb_state_unref(st.xkb_state);                                     /* all three are NULL-safe */
    xkb_keymap_unref(st.xkb_keymap);
    xkb_context_unref(st.xkb_context);
    xdg_toplevel_destroy(st.toplevel);
    xdg_surface_destroy(st.xdg_surface);
    wl_surface_destroy(st.surface);
    xdg_wm_base_destroy(st.wm_base);
    wl_shm_destroy(st.shm);
    wl_compositor_destroy(st.compositor);
    wl_registry_destroy(st.registry);
    wl_display_disconnect(st.display);
    return 0;
}
