/* hello_wayland: the smallest honest Wayland window.
 *
 * The whole program is the four-step pipeline:
 *
 *   role -> configure/ack handshake -> buffer -> commit
 *
 * Reading order: main() at the bottom, then jump to each callback
 * as it is mentioned. Written in plain C so every protocol step is
 * visible; no wrapper classes hiding anything.
 */

#define _GNU_SOURCE /* for memfd_create */

#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#include <wayland-client.h>

#include "xdg-shell-client-protocol.h" /* generated by wayland-scanner */

enum { WIDTH = 640, HEIGHT = 360 }; /* fallback size when the compositor has no opinion */

/* All state in one struct. This plays the role of your WaylandCore's
 * members; the "void* data" of every listener points here. */
struct state {
    /* connection + introduction phase */
    struct wl_display* display;
    struct wl_registry* registry;
    struct wl_compositor* compositor;
    struct wl_shm* shm;          /* shared-memory buffers (simplest kind) */
    struct xdg_wm_base* wm_base; /* the "make surfaces into windows" service */

    /* the window itself */
    struct wl_surface* surface;
    struct xdg_surface* xdg_surface;
    struct xdg_toplevel* toplevel;

    int running;

    /* Window size. STAGED by xdg_toplevel.configure (data, no serial),
     * CONSUMED when we ack in xdg_surface.configure (serial, no data).
     * The compositor sends 0 for "you pick" -> fall back to WIDTH/HEIGHT. */
    int pending_w;
    int pending_h;
};

/* ------------------------------------------------------------------ */
/* Step 0: the introduction phase. Identical in spirit to your        */
/* WaylandCore::on_global: read the menu, order what we need.         */
/* ------------------------------------------------------------------ */

static void on_global(void* data,
                      struct wl_registry* registry,
                      uint32_t name,
                      const char* interface,
                      uint32_t version) {
    struct state* st = data;
    (void)version;

    if (strcmp(interface, wl_compositor_interface.name) == 0) {
        st->compositor = wl_registry_bind(registry, name, &wl_compositor_interface, 4);
    } else if (strcmp(interface, wl_shm_interface.name) == 0) {
        st->shm = wl_registry_bind(registry, name, &wl_shm_interface, 1);
    } else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
        st->wm_base = wl_registry_bind(registry, name, &xdg_wm_base_interface, 1);
    }
}

static void on_global_remove(void* data, struct wl_registry* registry, uint32_t name) {
    (void)data;
    (void)registry;
    (void)name;
}

static const struct wl_registry_listener registry_listener = {
    .global = on_global,
    .global_remove = on_global_remove,
};

/* The liveness check: compositor pings, we must pong or be declared dead. */
static void on_wm_base_ping(void* data, struct xdg_wm_base* wm_base, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(wm_base, serial);
}

static const struct xdg_wm_base_listener wm_base_listener = {
    .ping = on_wm_base_ping,
};

/* ------------------------------------------------------------------ */
/* Step 3 (the buffer): pixel memory the compositor can see.          */
/*                                                                    */
/* wl_shm works like this: we create a plain memory file (memfd),     */
/* mmap it, draw into it, and pass the fd over the socket. Compositor */
/* maps the same file -> both sides see the same pixels, zero copy.   */
/* (Your zcc uses dmabuf: same idea, but GPU memory instead of RAM.)  */
/* ------------------------------------------------------------------ */

/* Buffer lifetime: we create a fresh buffer per configure, so old ones
 * must be freed -- but only once the compositor is done reading (it maps
 * the same memory!). It says so with the release event. */
static void on_buffer_release(void* data, struct wl_buffer* buffer) {
    (void)data;
    wl_buffer_destroy(buffer);
}

static const struct wl_buffer_listener buffer_listener = {
    .release = on_buffer_release,
};

static struct wl_buffer* draw_frame(struct state* st) {
    const int w = st->pending_w;
    const int h = st->pending_h;
    const int stride = w * 4; /* 4 bytes per pixel: XRGB8888 */
    const int size = stride * h;

    int fd = memfd_create("hello-wayland", 0);
    if (fd < 0 || ftruncate(fd, size) < 0) {
        perror("shm alloc");
        exit(1);
    }

    uint32_t* pixels = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (pixels == MAP_FAILED) {
        perror("mmap");
        exit(1);
    }

    /* The actual "rendering": fill with one color. 0x00RRGGBB. */
    for (int i = 0; i < w * h; i++) { pixels[i] = 0x00870299; /* a calm teal */ }
    munmap(pixels, size);

    /* Wrap the memory in protocol objects: pool = the whole file,
     * buffer = one image inside it. Then the fd can be closed;
     * the compositor holds its own reference. */
    struct wl_shm_pool* pool = wl_shm_create_pool(st->shm, fd, size);
    struct wl_buffer* buffer =
        wl_shm_pool_create_buffer(pool, 0, w, h, stride, WL_SHM_FORMAT_XRGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);

    wl_buffer_add_listener(buffer, &buffer_listener, NULL);
    return buffer;
}

/* ------------------------------------------------------------------ */
/* Step 2 (the handshake): the compositor answers our first commit    */
/* with a configure event. We must ack it, quoting its serial. Only   */
/* then may the surface carry content -- so this callback is also     */
/* where we attach the buffer. The commit at the end is the mapping   */
/* moment: this is when the window appears on screen.                 */
/*                                                                    */
/* The same callback serves every later resize: toplevel configure    */
/* staged pending_w/h, our ack promises "commits from now on answer   */
/* serial N", and we draw at the staged size -- so the compositor can */
/* swap geometry and content atomically in one frame.                 */
/* ------------------------------------------------------------------ */

static void on_xdg_surface_configure(void* data, struct xdg_surface* xdg_surface, uint32_t serial) {
    struct state* st = data;

    xdg_surface_ack_configure(xdg_surface, serial);

    struct wl_buffer* buffer = draw_frame(st);
    wl_surface_attach(st->surface, buffer, 0, 0);
    wl_surface_commit(st->surface);
}

static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = on_xdg_surface_configure,
};

/* Toplevel events: the compositor's size proposal and the close button.
 *
 * configure carries the DATA (w, h, states -- signature "iia") but no
 * serial: it only STAGES state, mirroring how our own requests are
 * pending until commit. Nothing is applied here; xdg_surface.configure
 * ends the batch and tells us when to act. */
static void on_toplevel_configure(void* data,
                                  struct xdg_toplevel* toplevel,
                                  int32_t w,
                                  int32_t h,
                                  struct wl_array* states) {
    (void)toplevel;
    (void)states; /* maximized/activated/resizing/... -- unused here */
    struct state* st = data;

    /* 0 means "you pick" -- typical for the very first configure,
     * which answers our empty commit. */
    st->pending_w = w > 0 ? w : WIDTH;
    st->pending_h = h > 0 ? h : HEIGHT;
}

static void on_toplevel_close(void* data, struct xdg_toplevel* toplevel) {
    (void)toplevel;
    struct state* st = data;
    st->running = 0;
}

static const struct xdg_toplevel_listener toplevel_listener = {
    .configure = on_toplevel_configure,
    .close = on_toplevel_close,
};

/* ------------------------------------------------------------------ */

int main(void) {
    struct state st = {0};
    st.running = 1;
    st.pending_w = WIDTH;
    st.pending_h = HEIGHT;

    /* Pick up the phone line. */
    st.display = wl_display_connect(NULL);
    if (!st.display) {
        fprintf(stderr, "no Wayland display (is WAYLAND_DISPLAY set?)\n");
        return 1;
    }

    /* Introduction phase: listen to the menu, bind services.
     * One roundtrip is enough here -- none of our three globals
     * sends initial events on bind (unlike dmabuf in zcc). */
    st.registry = wl_display_get_registry(st.display);
    wl_registry_add_listener(st.registry, &registry_listener, &st);
    wl_display_roundtrip(st.display);

    if (!st.compositor || !st.shm || !st.wm_base) {
        fprintf(stderr, "missing wl_compositor, wl_shm or xdg_wm_base\n");
        return 1;
    }
    xdg_wm_base_add_listener(st.wm_base, &wm_base_listener, &st);

    /* Step 0.5: the blank canvas -- what you created in lldb. */
    st.surface = wl_compositor_create_surface(st.compositor);

    /* Step 1: give it a role. Surface -> xdg_surface -> toplevel. */
    st.xdg_surface = xdg_wm_base_get_xdg_surface(st.wm_base, st.surface);
    xdg_surface_add_listener(st.xdg_surface, &xdg_surface_listener, &st);

    st.toplevel = xdg_surface_get_toplevel(st.xdg_surface);
    xdg_toplevel_add_listener(st.toplevel, &toplevel_listener, &st);
    xdg_toplevel_set_title(st.toplevel, "hello wayland");
    xdg_toplevel_set_app_id(st.toplevel, "hello-wayland");

    /* First commit: still WITHOUT a buffer. This tells the compositor
     * "role assigned, please configure me". The reply arrives as the
     * configure event -> on_xdg_surface_configure above. */
    wl_surface_commit(st.surface);

    /* The event loop: block, read mail, run callbacks, repeat.
     * Everything from here on happens inside the listeners. */
    while (st.running && wl_display_dispatch(st.display) != -1) {}

    /* Teardown mirror, same discipline as WaylandCore::disconnect. */
    xdg_toplevel_destroy(st.toplevel);
    xdg_surface_destroy(st.xdg_surface);
    wl_surface_destroy(st.surface);
    xdg_wm_base_destroy(st.wm_base);
    wl_shm_destroy(st.shm);
    wl_compositor_destroy(st.compositor);
    wl_registry_destroy(st.registry);
    wl_display_disconnect(st.display);
    return 0;
}
